version: "3"

services:

  jupyterhub:
    build: jupyter-hub
    image: wollac/jupyterhub
    container_name: jupyter_hub
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      DOCKER_JUPYTER_IMAGE: wollac/jupyter-datascience-pyscip
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      HUB_IP: jupyter_hub
    env_file:
      - secrets/oauth.env
    networks:
      - ${TRAEFIK_NETWORK}
      - jupyter
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"
      - "traefik.http.routers.jupyterhub.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.jupyterhub.tls.certResolver=default"
 
  jupyterlab:
    build: jupyter-notebook
    image: wollac/jupyter-datascience-pyscip
    container_name: jupyter_throwaway
    network_mode: none
    command: echo

networks:
  web:
    external: true

  jupyter:
    external:
      name: ${DOCKER_NETWORK_NAME}

